/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthassistant;

import java.sql.Connection;
import java.sql.SQLException;
import static java.util.Collections.list;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akhma
 */
public class RumahSakit extends javax.swing.JFrame {

    /**
     * Creates new form RumahSakit
     */
    public RumahSakit() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RS = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Rumah Sakit Yang Tersedia");

        jButton1.setText("Cek");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Kembali");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        RS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"RS A", "JL Mangga", "021XXX1"},
                {"RS B", "JL Mangga II", "021XXX2"},
                {"RS C", "JL Mangga III", "021XXX3"},
                {"RS D", "JL Mangga IV", "021XXX4"},
                {"RS E", "JL Mangga V", "021XXX5"},
                {"RS F", "JL Mangga VI", "021XXX6"},
                {"RS G", "JL Mangga VII", "021XXX7"},
                {"RS H", "JL Mangga VIII", "021XXX8"},
                {"RS I", "JL Mangga", "021XXX9"}
            },
            new String [] {
                "Nama", "Lokasi", "Kontak"
            }
        ));
        RS.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                RSPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(RS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     new MainMenu().setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void RSPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_RSPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_RSPropertyChange

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int position;
        position = this.RS.getSelectedRow();
        if (position == 0) {
            JOptionPane.showMessageDialog(this, "Rumah Sakit Ini Sudah Full");
        } else if (position == 1) {
            JOptionPane.showMessageDialog(this, "Silahkan Datang Langsung Pada Alamat Berikut \n JL Mangga II");
        } else if (position == 2) {
            JOptionPane.showMessageDialog(this, "Silahkan Datang Langsung Pada Alamat Berikut \n JL Mangga III");
        } else if (position == 3) {
            JOptionPane.showMessageDialog(this, "Silahkan Datang Langsung Pada Alamat Berikut \n JL Mangga IV");
        } else if (position == 4) {
            JOptionPane.showMessageDialog(this, "Silahkan Datang Langsung Pada Alamat Berikut \n JL Mangga V");
        } else if (position == 5) {
            JOptionPane.showMessageDialog(this, "Rumah Sakit Ini Sudah Full");
        } else if (position == 6) {
            JOptionPane.showMessageDialog(this, "Rumah Sakit Ini Sudah Full");
        } else if (position == 7) {
            JOptionPane.showMessageDialog(this, "Rumah Sakit Ini Sudah Full");
        } else if (position == 8) {
            JOptionPane.showMessageDialog(this, "Rumah Sakit Ini Sudah Full");
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Salah Satu");
        }
       
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RumahSakit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
